### ISSUE TITLE
Tambah Diskusi Project

### ISSUE THREAD

**Issue by alexwawo** [2017103583/FreelancerPod#6]
Tambahkan fitur diskusi.
Judul,
Isi,
Attachment (bisa lebih dari 1)
participant (siapa saja yang bisa lihat, pilih dari user yang ada di project, baik itu team/client)
participant bisa lebih dari 1.
Pilihan participant, bisa pilih satu per satu, atau di set umum/public (bisa dilihat semua anggota project-client/team)

**Comment by 2017103583** [comment]
finish
